name: Keep Streamlit App (softmax) Alive

on:
  schedule:
    - cron: "20 * * * *"  # 毎時20分ごとに実行（UTC時間）

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your Streamlit App (softmax)
        run: curl -s https://softmax-dxah7vapvidqb6wmvqcacy.streamlit.app/
